version: 2.1
jobs:
  deploy_build:
    docker:
      - image: circleci/node:8.11.4

    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - "f9:f3:e5:0b:5a:71:69:3a:63:5b:35:b1:4c:5e:24:59"

      - run:
          name: Install Meteor
          command: "curl https://install.meteor.com | /bin/sh"

      - restore_cache:
          key: dependency-cache-{{ checksum "./package.json" }}

      - run:
          name: Install packages
          command: |
            npm run setup

      - save_cache:
          key: dependency-cache-{{ checksum "./package.json" }}
          paths:
            - ./node_modules

      - run:
          name: Create Settings File
          command: echo $METEOR_SETTINGS > .deploy/settings.json

      - run:
          name: Use keyscan
          command: |
            ssh-keyscan $HOST >> ~/.ssh/known_hosts

      - run:
          name: Mup setup
          command: |
            cd ./.deploy
            npx mup setup

      - run:
          name: Mup deploy
          command: |
            cd ./.deploy
            npx mup deploy

workflows:
  version: 2
  Integration_and_delivery:
    jobs:
      - deploy_build:
          filters:
            branches:
              only: master
